# ~/.tmux.conf

# Terminal
if-shell 'infocmp tmux-256color >/dev/null 2>&1' \
  'set -g default-terminal tmux-256color' \
  'set -g default-terminal screen-256color'
set -as terminal-features ",xterm-256color:RGB"

# Window titles
setw -g automatic-rename on
set -g set-titles on
set -g set-titles-string "#T"

# Status bar
set -g status off
set -g status-style fg=colour15,bg=colour0
set -g status-left "P#{pane_index}  "
set -g status-right "%Y-%m-%d (%a)  %H:%M "
bind b set status

# Pane borders
set -g pane-border-style fg=colour0
set -g pane-active-border-style "bg=default fg=colour0"

# Use a different prefix on the ghost host.
if-shell '[ "$(hostname)" = ghost ]' {
  unbind C-Space
  set -g prefix C-Space
  bind C-Space send-prefix
}

# Preserve the current directory when creating panes and windows.
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vi mode
setw -g mode-keys vi
set -s escape-time 0

# Copy mode
set -g set-clipboard off
bind P paste-buffer
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

if-shell 'command -v pbcopy >/dev/null 2>&1' {
  bind-key -T copy-mode-vi y send-keys -X copy-pipe "pbcopy"
  bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "pbcopy"
} {
  if-shell 'command -v wl-copy >/dev/null 2>&1' {
    bind-key -T copy-mode-vi y send-keys -X copy-pipe "wl-copy"
    bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "wl-copy"
  } {
    if-shell 'command -v xclip >/dev/null 2>&1' {
      bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard"
      bind-key -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
    }
  }
}

set -g history-limit 5000

# Pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing
bind -n C-S-Up resize-pane -U
bind -n C-S-Down resize-pane -D
bind -n C-S-Left resize-pane -L
bind -n C-S-Right resize-pane -R
bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5
bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5

# Miscellaneous
bind S setw synchronize-panes
bind R source-file ~/.tmux.conf
