#!/bin/bash

# @author       clemedon (Clément Vidon)
# @brief        Rename my phone pictures YYMMDD_DayCount.HEIC
#
# Also generate a hidden undo script in the target directory.
#
# @param[in]    a directory that contains the files to rename
# @see http://mywiki.wooledge.org/ParsingLs

if [ ! $1 ]
then
    echo "You have to specify a target directory"
    exit
fi
# TODO check if folder not empty

prevtime=000000 # the timestamp of the previous file
currtime=000000     # the timestamp of the current file
n=1           # file count on the same day

# prefix files with their YYMMDDHHMMSS last modification time stamp so they are
# read in this order by glob function that fill the 'files' array.
for f in $1/*; do
    mv -vn "$f" "$1/"$(date -r "$f" +"%g%m%d%H%M%S")_"$(basename "$f")"
done

declare -a files=( $1/* )
for (( i = 0; i < ${#files[*]}; ++ i ))
do

    currtime=$(date -r "${files[$i]}" +"%g%m%d")

    [[ $i -gt 0 ]] && prevtime=$(date -r "$newfile" +"%g%m%d")
    [[ "$currtime" != "$prevtime" ]] && n=1

    ext="${files[$i]##*.}"
    newfile=$1/"CV_$currtime"_"$(printf "%03d\n" "$n")".$ext

    mv -vn "${files[$i]}" "$newfile"

    oldfile=$(basename "${files[$i]}")
    oldfile=${oldfile:13}
    echo "mv -v \"$newfile\" \"$1/$oldfile\"" >> $1/.undo_$(date +"%g%m%d%H%M%S".sh)
    let "n=$n+1"
done
