#!/bin/bash

NET_MONTH="$1"
WORKDAY_PER_MONTH=15
WORKHOUR_PER_DAY=8
PCT_COTISATIONS_SOCIALES=22 # not 80!!!
EUR_MUTUELLE_TNS=50
EUR_ASSURANCE_CHOMAGE=90
EUR_ASSURANCE_RS=30
PCT_FRAIS_FONCTIONNEMENT=10

# Check if the script received exactly one argument
if [ "$#" -ne 1 ]; then
    echo "Usage: tjm <salaire net désiré>"
    exit 1
fi

# Check if the argument is a valid number
if ! [[ $1 =~ ^[0-9]+$ ]]; then
    echo "Error: The argument must be a valid number."
    exit 1
fi

# Compute the TJM based on the NET Salary
echo "$NET_MONTH + cotisations sociales $PCT_COTISATIONS_SOCIALES PCT"
TJM=$(($NET_MONTH + ($NET_MONTH * $PCT_COTISATIONS_SOCIALES / 100)))

echo "$TJM + contrat de mutuelle TNS $EUR_MUTUELLE_TNS EUR"
TJM=$(($TJM + $EUR_MUTUELLE_TNS))

echo "$TJM + assurance chomage $EUR_ASSURANCE_CHOMAGE EUR"
TJM=$(($TJM + $EUR_ASSURANCE_CHOMAGE))

echo "$TJM + assurance responsabilite civile pro $EUR_ASSURANCE_RS EUR"
TJM=$(($TJM + $EUR_ASSURANCE_RS))

echo "$TJM + frais de fonctionnement $PCT_FRAIS_FONCTIONNEMENT PCT"
TJM=$(($TJM + ($TJM * $PCT_FRAIS_FONCTIONNEMENT / 100)))

BRUT_MONTH=$TJM

TJM=$(($TJM/$WORKDAY_PER_MONTH))
THM=$(($TJM/$WORKHOUR_PER_DAY))

BRUT_YEAR=$(($BRUT_MONTH*12))
NET_YEAR=$(($NET_MONTH*12))

echo "-- NET --"
echo "YEAR:     $NET_YEAR"
echo "MONTH:    $NET_MONTH"
echo "-- BRUT --"
echo "YEAR      $BRUT_YEAR"
echo "MONTH     $BRUT_MONTH"
echo "TJM BRUT: $TJM"
echo "THM BRUT: $THM"
