#!/bin/bash
# a simple logout dialog

# launch exit menu
choice=`echo -e "0: lock\n1: logout\n2: suspend\n3: hibernate\n4: reboot\n5: shutdown\n6: cancel" | dmenu -p "select an action" | cut -d ':' -f 1`

lock() {
    i3lock \
        --no-unlock-indicator \
        --color=000050 \
        --ignore-empty-password \
        --nofork
    }

# execute the choice in background
case "$choice" in
    0) lock ;;
    1) i3-msg exit & ;;
    2) lock && systemctl suspend & ;;
    3) lock && systemctl hibernate & ;;
    4) systemctl reboot & ;;
    5) systemctl poweroff & ;;
esac
